apiVersion: skaffold/v2beta29
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: oscka/java-demo-api
#        - image: java-demo-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: eclipse-temurin:17.0.2_8-jre
    deploy:
      kubectl:
        manifests:
          - k8s/dev/demo-api-deploy.yaml
          - k8s/dev/domo-api-ingress.yaml
    # portForward:
    # - resourceType: service
    #   resourceName: demo-api-svc
    #   namespace: api
    #   port: 8080
    #   localPort: 9320