apiVersion: v1
kind: Service

metadata:
  name: demo-api-svc
  namespace: api
spec:
  selector:
    app: demo-api
  
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: http


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-deploy
  namespace: api    
  
  labels:
    app: demo-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      
      labels:
        app: demo-api     
      

    spec:
      containers:
        - name: demo-api
          image: demo-api
          ports:
          - name: http
            containerPort: 8080
  
